---
title: Week 3 - Stats Exam
sitetitle: Week 3 - Stats Exam
summary: "EC200 - Week 3 Exam 1 Prep (Statistics)"
date: "2022-01-19"
start_date: "2022-01-31"
end_date: "2022-02-04"
  # Academic page type (do not modify).
type: docs
menu:
  content:
    parent: Course content
    weight: 3
output:
  blogdown::html_page:
    toc: true
pdf: /slides/ch3-slides.pdf
thumb: /slides/ch3-slides.png



---

## What should I know? 

Make sure you are comfortable with the material chapter guides from [Week 1](../01-content) and  [Week 2](../02-content). What does comfortable mean? That you're familiar with definitions and terminology, and that you can work through problems at the level of PS1 (solutions on [Blackboard](http://bb.uvm.edu)).

There will not be a Stata component to the exam. 

## I need more practice!

I recommend the following resources: 

 - Odd-numbered problems from Stock and Watson - solutions are available [here](../../bonus/general-resources)
 - [Practice exam](#practice-exam)
 - [In-class practice](#inclass-practice)

## What is the structure of the exam? 

The exam will be a lot like a math exam - solving some problems and showing your work. I would expect about 3 multi-part questions. There may be some questions that involve definitions and/or true-false.


The exam is open book with a calculator allowed. 

What is allowed?

  - Paper notes
  - Textbook
  - Calculator (basic, scientific, graphing)
  
What is not allowed?

  - ~~Phone~~ 
  - ~~Tablet~~
  - ~~Laptop~~



<!---### How do I submit? 
Work through on paper, then scan a copy and upload it onto Blackboard. Please use something like [Adobe Scan](https://acrobat.adobe.com/us/en/mobile/scanner-app.html) so that you can submit **just one file in pdf form**. In the past, I've found that uploading photos yields huge files that are difficult to grade.

#### Details: 

What should you make sure you include? 

 - Just one file per person 
 - PDF version - review in advance to make sure the text is readable
 - Make sure your answers are numbered, but you don't need to write out the questions
 - Please make sure pages are in order
 - **YOU MUST SHOW YOUR WORK** for full credit. 
--->

### In-class practice 

[Here are the problems](../practice/EC200-03-01practice.pdf) we covered in class.


And a video with solutions! I recommend working through the problems on your own **first**. 

`r htmltools::HTML("{{< youtube q_NbBSDWcpI >}}")`

Or, download a [pdf of the solutions](../practice/EC200-03-01practice_solutions.pdf)

<!---
### Practice exam! (For logisitics)

Just to make sure we're feeling good about logistics, I'll post a "practice exam" on Blackboard that will go live at **3:30pm on Friday, September 18** (after our optional meet up) with one question. You can download it, work through the problem, scan it and upload your exam.  It will be available until **11:59 pm Sunday.**

I'll review your submission and make sure there aren't any problems with viewing your work.  

Completion of the practice exam will be worth 2 points toward the exam (regardless of the accuracy of your answer).

 

## Practice 

On Friday, I'll release an optional "practice" lock-down exam. It will have one practice questions, so we can all experience the glory of online testing. If you complete the pratice lock-down exam, you will earn 2 points toward the exam.
--> 

## Helpful materials {#helpful-materials}

Two things that may be useful to you: 

- [Standard Normal Distribution Table](../AppendixTable1_rev.pdf)

- [Formula chart](../Formula-sheet_f20.pdf): Is this all the knowledge you need to know? Of course not! But, this should cover most of the formulas you might need. 

## Past exam  {#practice-exam .unnumbered}


[Fall 2018 Practice Exam](../PracticeExams/StatsQuiz_Spring2018_print.pdf)

[Fall 2018 Practice Exam Solutions](../PracticeExams/StatsQuiz_Spring2018_sol.pdf) (*I strongly recommend doing the practice exam in its entirety before reviewing the solutions*)
