<!DOCTYPE html>
<html lang="en"><head>
<script src="ch5_hypothesis_tests_new_files/libs/clipboard/clipboard.min.js"></script>
<script src="ch5_hypothesis_tests_new_files/libs/quarto-html/tabby.min.js"></script>
<script src="ch5_hypothesis_tests_new_files/libs/quarto-html/popper.min.js"></script>
<script src="ch5_hypothesis_tests_new_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="ch5_hypothesis_tests_new_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="ch5_hypothesis_tests_new_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="ch5_hypothesis_tests_new_files/libs/quarto-html/quarto-syntax-highlighting-597958c53c93a607afca12fd375c57ed.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
 <meta name="generator" content="quarto-1.8.26">

 <meta name="author" content="ECON3500: Econometrics and Applications">
 <title>Hypothesis Tests and Confidence Intervals</title>
 <meta name="apple-mobile-web-app-capable" content="yes">
 <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
 <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
 <link rel="stylesheet" href="ch5_hypothesis_tests_new_files/libs/revealjs/dist/reset.css">
 <link rel="stylesheet" href="ch5_hypothesis_tests_new_files/libs/revealjs/dist/reveal.css">
 <style>
 code{white-space: pre-wrap;}
 span.smallcaps{font-variant: small-caps;}
 div.columns{display: flex; gap: min(4vw, 1.5em);}
 div.column{flex: auto; overflow-x: auto;}
 div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
 ul.task-list{list-style: none;}
 ul.task-list li input[type="checkbox"] {
 width: 0.8em;
 margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
 vertical-align: middle;
 }
 /* CSS for syntax highlighting */
 html { -webkit-text-size-adjust: 100%; }
 pre > code.sourceCode { white-space: pre; position: relative; }
 pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
 pre > code.sourceCode > span:empty { height: 1.2em; }
 .sourceCode { overflow: visible; }
 code.sourceCode > span { color: inherit; text-decoration: inherit; }
 div.sourceCode { margin: 1em 0; }
 pre.sourceCode { margin: 0; }
 @media screen {
 div.sourceCode { overflow: auto; }
 }
 @media print {
 pre > code.sourceCode { white-space: pre-wrap; }
 pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
 }
 pre.numberSource code
 { counter-reset: source-line 0; }
 pre.numberSource code > span
 { position: relative; left: -4em; counter-increment: source-line; }
 pre.numberSource code > span > a:first-child::before
 { content: counter(source-line);
 position: relative; left: -1em; text-align: right; vertical-align: baseline;
 border: none; display: inline-block;
 -webkit-touch-callout: none; -webkit-user-select: none;
 -khtml-user-select: none; -moz-user-select: none;
 -ms-user-select: none; user-select: none;
 padding: 0 4px; width: 4em;
 }
 pre.numberSource { margin-left: 3em; padding-left: 4px; }
 div.sourceCode
 { color: #24292e; }
 @media screen {
 pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
 }
 code span { color: #24292e; } /* Normal */
 code span.al { color: #ff5555; font-weight: bold; } /* Alert */
 code span.an { color: #6a737d; } /* Annotation */
 code span.at { color: #d73a49; } /* Attribute */
 code span.bn { color: #005cc5; } /* BaseN */
 code span.bu { color: #d73a49; } /* BuiltIn */
 code span.cf { color: #d73a49; } /* ControlFlow */
 code span.ch { color: #032f62; } /* Char */
 code span.cn { color: #005cc5; } /* Constant */
 code span.co { color: #6a737d; } /* Comment */
 code span.cv { color: #6a737d; } /* CommentVar */
 code span.do { color: #6a737d; } /* Documentation */
 code span.dt { color: #d73a49; } /* DataType */
 code span.dv { color: #005cc5; } /* DecVal */
 code span.er { color: #ff5555; text-decoration: underline; } /* Error */
 code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
 code span.fl { color: #005cc5; } /* Float */
 code span.fu { color: #6f42c1; } /* Function */
 code span.im { color: #032f62; } /* Import */
 code span.in { color: #6a737d; } /* Information */
 code span.kw { color: #d73a49; } /* Keyword */
 code span.op { color: #24292e; } /* Operator */
 code span.ot { color: #6f42c1; } /* Other */
 code span.pp { color: #d73a49; } /* Preprocessor */
 code span.re { color: #6a737d; } /* RegionMarker */
 code span.sc { color: #005cc5; } /* SpecialChar */
 code span.ss { color: #032f62; } /* SpecialString */
 code span.st { color: #032f62; } /* String */
 code span.va { color: #e36209; } /* Variable */
 code span.vs { color: #032f62; } /* VerbatimString */
 code span.wa { color: #ff5555; } /* Warning */
 </style>
 <link rel="stylesheet" href="ch5_hypothesis_tests_new_files/libs/revealjs/dist/theme/quarto-f6ff266a00026af0db213e5461a2bde6.css">
 <link rel="stylesheet" href="styles.css">
 <link href="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
 <link href="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
 <link href="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
 <link href="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
 <link href="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
 <link href="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
 <style type="text/css">
 .reveal div.sourceCode {
 margin: 0;
 overflow: auto;
 }
 .reveal div.hanging-indent {
 margin-left: 1em;
 text-indent: -1em;
 }
 .reveal .slide:not(.center) {
 height: 100%;
 overflow-y: auto;
 }
 .reveal .slide.scrollable {
 overflow-y: auto;
 }
 .reveal .footnotes {
 height: 100%;
 overflow-y: auto;
 }
 .reveal .slide .absolute {
 position: absolute;
 display: block;
 }
 .reveal .footnotes ol {
 counter-reset: ol;
 list-style-type: none; 
 margin-left: 0;
 }
 .reveal .footnotes ol li:before {
 counter-increment: ol;
 content: counter(ol) ". "; 
 }
 .reveal .footnotes ol li > p:first-child {
 display: inline-block;
 }
 .reveal .slide ul,
 .reveal .slide ol {
 margin-bottom: 0.5em;
 }
 .reveal .slide ul li,
 .reveal .slide ol li {
 margin-top: 0.4em;
 margin-bottom: 0.2em;
 }
 .reveal .slide ul[role="tablist"] li {
 margin-bottom: 0;
 }
 .reveal .slide ul li > *:first-child,
 .reveal .slide ol li > *:first-child {
 margin-block-start: 0;
 }
 .reveal .slide ul li > *:last-child,
 .reveal .slide ol li > *:last-child {
 margin-block-end: 0;
 }
 .reveal .slide .columns:nth-child(3) {
 margin-block-start: 0.8em;
 }
 .reveal blockquote {
 box-shadow: none;
 }
 .reveal .tippy-content>* {
 margin-top: 0.2em;
 margin-bottom: 0.7em;
 }
 .reveal .tippy-content>*:last-child {
 margin-bottom: 0.2em;
 }
 .reveal .slide > img.stretch.quarto-figure-center,
 .reveal .slide > img..quarto-figure-center {
 display: block;
 margin-left: auto;
 margin-right: auto; 
 }
 .reveal .slide > img.stretch.quarto-figure-left,
 .reveal .slide > img..quarto-figure-left {
 display: block;
 margin-left: 0;
 margin-right: auto; 
 }
 .reveal .slide > img.stretch.quarto-figure-right,
 .reveal .slide > img..quarto-figure-right {
 display: block;
 margin-left: auto;
 margin-right: 0; 
 }
 </style>
</head>
<body class="quarto-light">
 <div class="reveal">
 <div class="slides">

<section id="title-slide" class="quarto-title-block center">
 <h1 class="title">Hypothesis Tests and Confidence Intervals</h1>
 <p class="subtitle">From Uncertainty to Evidence-Based Conclusions</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
ECON3500: Econometrics and Applications 
</div>
</div>
</div>

 <p class="date">Spring 2026</p>
</section>
<section id="roadmap" class="slide level2">
<h2>Roadmap</h2>
<p><strong>Central question</strong></p>
<p>We have an estimate <span class="math inline">\(\hat\beta_1\)</span>, but is it <strong>reliable evidence</strong> for a relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>?</p>
<p><strong>By the end of this chapter, you will be able to:</strong></p>
<ul>
<li>Test hypotheses about <span class="math inline">\(\beta_1\)</span> using <span class="math inline">\(t\)</span>-statistics</li>
<li>Construct and interpret confidence intervals</li>
<li>Work with <strong>binary regressors</strong> (dummy variables)</li>
<li>Understand <strong>heteroskedasticity</strong> and use robust standard errors</li>
<li>Know when OLS is <strong>BLUE</strong> (Gauss–Markov Theorem)</li>
</ul>
</section>
<section id="the-inference-roadmap" class="slide level2 scrollable">
<h2>The Inference Roadmap</h2>
<p><strong>Here’s where we’re headed today:</strong></p>
<ol type="1">
<li><strong>Estimate</strong> <span class="math inline">\(\hat\beta_1\)</span> with OLS (Chapter 4 review)</li>
<li><strong>Compute</strong> <span class="math inline">\(\text{SE}(\hat\beta_1)\)</span> using robust standard errors</li>
<li><strong>Test hypotheses</strong> using <span class="math inline">\(t\)</span>-statistics and <span class="math inline">\(p\)</span>-values</li>
<li><strong>Construct confidence intervals</strong> to quantify uncertainty</li>
<li><strong>Interpret results</strong>: statistical <strong>and</strong> economic significance</li>
<li><strong>Handle special cases</strong>: binary variables, heteroskedasticity</li>
</ol>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p><strong>Watch for the roadmap.</strong><br>
We’ll reference this roadmap as we go (look for “Step X” markers).</p>
</div>
</div>
</div>
</section>
<section>
<section id="testing-hypotheses-about-beta_1" class="title-slide slide level1 center">
<h1>Testing Hypotheses About <span class="math inline">\(\beta_1\)</span></h1>

</section>
<section id="the-challenge-sampling-uncertainty" class="slide level2">
<h2>The Challenge: Sampling Uncertainty</h2>
<p>Recall from Chapter 4:</p>
<ul>
<li>We estimated <span class="math inline">\(\hat\beta_1 = 0.80\)</span> (effect of height on income)</li>
<li>But this is just <strong>one sample</strong> from the population</li>
<li>If we drew a different sample, we’d get a different <span class="math inline">\(\hat\beta_1\)</span></li>
<li><strong>Question:</strong> How confident can we be that the true <span class="math inline">\(\beta_1 \neq 0\)</span>?</li>
</ul>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Core Problem</strong></p>
</div>
<div class="callout-content">
<p><span class="math inline">\(\hat\beta_1\)</span> is a <strong>random variable</strong> with its own sampling distribution.<br>
We need a framework to separate <strong>signal</strong> from <strong>noise</strong>.</p>
</div>
</div>
</div>
</section>
<section id="sampling-distribution-of-hatbeta_1-review" class="slide level2">
<h2>Sampling Distribution of <span class="math inline">\(\hat\beta_1\)</span> (Review)</h2>
<p>Under the least squares assumptions, for large <span class="math inline">\(n\)</span>:</p>
<p><span class="math display">\[
\hat\beta_1 \sim N\left(\beta_1,\ \frac{\sigma^2_v}{n \cdot \operatorname{Var}(X)}\right),
\]</span></p>
<p>where <span class="math inline">\(v_i = (X_i - \mu_X)u_i\)</span>.</p>
<p><strong>Key insight:</strong></p>
<ul>
<li><span class="math inline">\(\hat\beta_1\)</span> is centered at the true <span class="math inline">\(\beta_1\)</span> (unbiased)</li>
<li>The spread (variance) depends on sample size <span class="math inline">\(n\)</span>, variation in <span class="math inline">\(X\)</span>, and error variance</li>
<li>By the Central Limit Theorem, <span class="math inline">\(\hat\beta_1\)</span> is approximately normal in large samples</li>
</ul>
</section>
<section id="setting-up-a-hypothesis-test" class="slide level2">
<h2>Setting Up a Hypothesis Test</h2>
<p><strong>Null hypothesis</strong> <span class="math inline">\(H_0\)</span>: the claim we’re testing.<br>
<strong>Alternative hypothesis</strong> <span class="math inline">\(H_1\)</span>: what we suspect if <span class="math inline">\(H_0\)</span> is false.</p>
<p><strong>Two-tailed test</strong></p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_{1,0} \quad \text{vs} \quad H_1: \beta_1 \neq \beta_{1,0}.
\]</span></p>
<p><strong>One-tailed tests</strong></p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_{1,0} \quad \text{vs} \quad H_1: \beta_1 &gt; \beta_{1,0}
\]</span></p>
<p>or</p>
<p><span class="math display">\[
H_0: \beta_1 = \beta_{1,0} \quad \text{vs} \quad H_1: \beta_1 &lt; \beta_{1,0}
\]</span></p>
<p>where <span class="math inline">\(\beta_{1,0}\)</span> is the hypothesized value under the null (often 0).</p>
</section>
<section id="the-t-statistic-our-test-statistic" class="slide level2">
<h2>The <span class="math inline">\(t\)</span>-Statistic: Our Test Statistic</h2>
<p><strong>General formula for any hypothesis test</strong></p>
<p><span class="math display">\[
t = \frac{\text{estimator} - \text{hypothesized value}}{\text{SE of estimator}}.
\]</span></p>
<p><strong>For testing <span class="math inline">\(H_0: \beta_1 = \beta_{1,0}\)</span>:</strong></p>
<p><span class="math display">\[
t = \frac{\hat\beta_1 - \beta_{1,0}}{\operatorname{SE}(\hat\beta_1)}.
\]</span></p>
<p><strong>Interpretation</strong></p>
<ul>
<li>Measures how many standard errors <span class="math inline">\(\hat\beta_1\)</span> is away from <span class="math inline">\(\beta_{1,0}\)</span></li>
<li>If <span class="math inline">\(|t|\)</span> is large, <span class="math inline">\(\hat\beta_1\)</span> is far from <span class="math inline">\(\beta_{1,0}\)</span> <span class="math inline">\(\Rightarrow\)</span> evidence against <span class="math inline">\(H_0\)</span></li>
<li>Under <span class="math inline">\(H_0\)</span>, <span class="math inline">\(t \sim N(0,1)\)</span> in large samples</li>
</ul>
</section>
<section id="decision-rule-when-to-reject-h_0" class="slide level2">
<h2>Decision Rule: When to Reject (H_0)</h2>

<img src="Lab/figures/ch5_rejection_regions.png" style="width:85.0%" class=" quarto-figure-center"><p class="caption">Rejection regions for one- and two-sided tests</p><p><strong>Reject <span class="math inline">\(H_0\)</span> at significance level <span class="math inline">\(\alpha\)</span> if:</strong></p>
<ul>
<li>Two-tailed: <span class="math inline">\(|t| &gt; c_{\alpha/2}\)</span></li>
<li>One-tailed (upper): <span class="math inline">\(t &gt; c_{\alpha}\)</span></li>
<li>One-tailed (lower): <span class="math inline">\(t &lt; -c_{\alpha}\)</span></li>
</ul>
</section>
<section id="one-tailed-vs-two-tailed-tests" class="slide level2">
<h2>One-Tailed vs Two-Tailed Tests</h2>

<img src="Lab/figures/ch5_one_vs_two_tailed.png" style="width:95.0%" class=" quarto-figure-center"><p class="caption">One- vs two-tailed tests</p><p><strong>Which to use?</strong></p>
<ul>
<li>Two-tailed: Most common in economics (test for any effect)</li>
<li>One-tailed: When theory strongly predicts a direction</li>
</ul>
</section>
<section id="critical-values-for-common-significance-levels" class="slide level2">
<h2>Critical Values for Common Significance Levels</h2>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Significance level <span class="math inline">\(\alpha\)</span></strong></th>
<th style="text-align: right;"><strong>Two-tailed <span class="math inline">\(c_{\alpha/2}\)</span></strong></th>
<th style="text-align: right;"><strong>One-tailed <span class="math inline">\(c_{\alpha}\)</span></strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>10%</td>
<td style="text-align: right;">1.645</td>
<td style="text-align: right;">1.28</td>
</tr>
<tr class="even">
<td>5%</td>
<td style="text-align: right;">1.96</td>
<td style="text-align: right;">1.645</td>
</tr>
<tr class="odd">
<td>1%</td>
<td style="text-align: right;">2.58</td>
<td style="text-align: right;">2.33</td>
</tr>
</tbody>
</table>
<p><strong>Rule of thumb:</strong> For two-tailed tests at 5%, reject if <span class="math inline">\(|t| &gt; 2\)</span>.</p>
<p>Requirements:</p>
<ul>
<li>Large sample (<span class="math inline">\(n &gt; 30\)</span> as a minimum for CLT to apply)</li>
<li>All three least squares assumptions hold</li>
</ul>
</section>
<section id="knowledge-check-calculate-the-t-statistic" class="slide level2 scrollable">
<h2>Knowledge Check: Calculate the <span class="math inline">\(t\)</span>-Statistic</h2>
<p><strong>Question</strong></p>
<p>You estimate <span class="math inline">\(\hat\beta_1 = 3.5\)</span> with <span class="math inline">\(\operatorname{SE}(\hat\beta_1) = 1.2\)</span>.<br>
Test <span class="math inline">\(H_0: \beta_1 = 0\)</span> vs <span class="math inline">\(H_1: \beta_1 \neq 0\)</span> at 5% level.</p>
<ol type="1">
<li>What is the <span class="math inline">\(t\)</span>-statistic?</li>
<li>What is your decision?</li>
</ol>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Answer</strong></p>
</div>
<div class="callout-content">
<ol type="1">
<li><span class="math inline">\(t = \dfrac{3.5 - 0}{1.2} = 2.92\)</span></li>
<li>Since <span class="math inline">\(|2.92| &gt; 1.96\)</span>, <strong>reject <span class="math inline">\(H_0\)</span></strong> at 5% level.<br>
Conclusion: strong evidence that <span class="math inline">\(\beta_1 \neq 0\)</span>.</li>
</ol>
</div>
</div>
</div>
</section>
<section id="type-i-and-type-ii-errors" class="slide level2">
<h2>Type I and Type II Errors</h2>

<img src="Lab/figures/ch5_type_errors.png" style="width:85.0%" class=" quarto-figure-center"><p class="caption">Type I and Type II errors</p><ul>
<li><strong>Type I error (<span class="math inline">\(\alpha\)</span>)</strong>: Reject <span class="math inline">\(H_0\)</span> when it’s true (false positive)</li>
<li><strong>Type II error (<span class="math inline">\(\beta\)</span>)</strong>: Fail to reject <span class="math inline">\(H_0\)</span> when it’s false (false negative)</li>
<li><strong>Power <span class="math inline">\((1-\beta)\)</span></strong>: Probability of correctly rejecting false <span class="math inline">\(H_0\)</span></li>
</ul>
</section>
<section id="choosing-a-significance-level" class="slide level2">
<h2>Choosing a Significance Level</h2>
<p><strong>Why (= 0.05) is conventional</strong></p>
<ul>
<li>We tolerate a 5% chance of false positives</li>
<li>Balances Type I and Type II errors</li>
<li>Widely accepted standard in social sciences</li>
</ul>
<p><strong>The tradeoff</strong></p>
<ul>
<li>Smaller () () fewer false positives, but <strong>more</strong> false negatives (lower power)</li>
<li>Larger () () more false positives, but <strong>fewer</strong> false negatives (higher power)</li>
<li>You cannot minimize both at once.</li>
</ul>
<p>We typically fix () and try to increase power by increasing (n).</p>
</section>
<section id="statistical-power" class="slide level2">
<h2>Statistical Power</h2>

<img src="Lab/figures/ch5_power_curve.png" style="width:75.0%" class=" quarto-figure-center"><p class="caption">Power curve</p><p>Power increases with:</p>
<ul>
<li>Larger true effect size (|_1|)</li>
<li>Larger sample size (n)</li>
<li>Smaller error variance (^2_u)</li>
</ul>
</section>
<section id="understanding-p-values" class="slide level2">
<h2>Understanding (p)-Values</h2>

<img src="Lab/figures/ch5_pvalue.png" style="width:85.0%" class=" quarto-figure-center"><p class="caption">p-value illustration</p><p><strong>(p)-value interpretation</strong></p>
<ul>
<li>Probability of observing a (t)-statistic this extreme (or more) if (H_0) is true</li>
<li>Smaller (p)-value () stronger evidence against (H_0)</li>
<li>Reject (H_0) if (p &lt; )</li>
</ul>
</section>
<section id="hypothesis-testing-in-stata" class="slide level2">
<h2>Hypothesis Testing in Stata</h2>
<p>**Testing (H_0: _1 = 0)**</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Stata output automatically shows:</p>
<ul>
<li>Coefficient estimate (_1)</li>
<li>Standard error ((_1))</li>
<li>(t)-statistic (t = _1 / (_1))</li>
<li>(p)-value: probability of observing (|t|) this large if (H_0) is true</li>
</ul>
<p><strong>Decision rule using (p)-value</strong></p>
<ul>
<li>Reject (H_0) if (p)-value &lt; ()</li>
<li>Equivalent to checking if (|t| &gt; c_{/2})</li>
</ul>
</section>
<section id="testing-h_0-_1-a-non-zero-null" class="slide level2">
<h2>Testing (H_0: _1 = a) (Non-Zero Null)</h2>
<p><strong>What if we want to test a different null value?</strong></p>
<p>Suppose we hypothesize that an extra year of education increases wage by exactly $3/hour:</p>
<p>[ H_0: _1 = 3 H_1: _1 . ]</p>
<p>Modified (t)-statistic:</p>
<p>[ t = . ]</p>
<p><strong>Example</strong></p>
<ul>
<li>If (_1 = 2.5) and ((_1) = 0.4), then (t = (2.5 - 3)/0.4 = -1.25)</li>
<li>Since (|-1.25| &lt; 1.96), <strong>fail to reject</strong> (H_0: _1 = 3)</li>
<li>Not enough evidence to say the effect differs from $3</li>
</ul>
</section>
<section id="economic-vs-statistical-significance" class="slide level2">
<h2>Economic vs Statistical Significance</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Critical distinction</strong></p>
</div>
<div class="callout-content">
<p><strong>Statistical significance</strong> () <strong>economic significance</strong>.</p>
</div>
</div>
</div>
<p><strong>Scenario 1: Statistically significant but economically trivial</strong></p>
<ul>
<li>(_1 = 0.05), ((_1) = 0.01), (t = 5) (highly significant!)</li>
<li>An extra year of education increases wage by 5 cents/hour</li>
<li>Technically significant, but economically negligible</li>
</ul>
<p><strong>Scenario 2: Economically important but statistically insignificant</strong></p>
<ul>
<li>(_1 = 8), ((_1) = 10), (t = 0.8) (not significant)</li>
<li>Small sample () high uncertainty</li>
<li>Effect could be large, but we can’t be confident</li>
</ul>
<p><strong>Takeaway:</strong> Always examine both statistical significance <strong>and</strong> magnitude.</p>
</section></section>
<section>
<section id="confidence-intervals-for-_1" class="title-slide slide level1 center">
<h1>Confidence Intervals for (_1)</h1>

</section>
<section id="from-hypothesis-tests-to-confidence-intervals" class="slide level2 scrollable">
<h2>From Hypothesis Tests to Confidence Intervals</h2>
<ul>
<li><strong>Hypothesis test:</strong> Is (_1) equal to a specific value?</li>
<li><strong>Confidence interval:</strong> What is a <strong>plausible range</strong> for (_1)?</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>95% Confidence Interval</strong></p>
</div>
<div class="callout-content">
<p>A random interval that contains the true parameter 95% of the time in repeated samples.</p>
</div>
</div>
</div>
<p>Two equivalent interpretations:</p>
<ol type="1">
<li>The set of all null values we <strong>cannot reject</strong> at 5% level</li>
<li>An interval constructed from the data that <strong>covers the truth</strong> 95% of the time</li>
</ol>
</section>
<section id="constructing-a-95-confidence-interval" class="slide level2">
<h2>Constructing a 95% Confidence Interval</h2>
<p>Since</p>
<p>[ t = N(0,1) ]</p>
<p>for large samples,</p>
<p>[ P( -1.96 &lt; &lt; 1.96 ) = 0.95. ]</p>
<p>Rearranging,</p>
<p>[ P( _1 - 1.96(_1) &lt; _1 &lt; _1 + 1.96 (_1) ) = 0.95. ]</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>95% Confidence Interval Formula</strong></p>
</div>
<div class="callout-content">
<p>[ _1 (_1). ]</p>
</div>
</div>
</div>
</section>
<section id="visualizing-confidence-intervals" class="slide level2">
<h2>Visualizing Confidence Intervals</h2>

<img src="Lab/figures/ch5_confidence_intervals.png" style="width:65.0%" class=" quarto-figure-center"><p class="caption">Many repeated 95% confidence intervals</p><ul>
<li>Each horizontal line is a 95% CI from a different sample</li>
<li>Teal intervals contain true (_1); gold ones miss</li>
<li>In the long run, <strong>95% of CIs</strong> will contain the truth</li>
</ul>
</section>
<section id="knowledge-check-interpret-a-confidence-interval" class="slide level2">
<h2>Knowledge Check: Interpret a Confidence Interval</h2>
<p><strong>Question</strong></p>
<p>You estimate the effect of job training on earnings:<br>
(_1 = 4.2) with 95% CI of ([1.8, 6.6]) (in $1000s/year).</p>
<p>Which statement is correct?</p>
<p>A. There is a 95% probability that (_1 )<br>
B. 95% of people see earnings gains between $1.8k and $6.6k<br>
C. We are 95% confident the true effect is between $1.8k and $6.6k</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Answer</strong></p>
</div>
<div class="callout-content">
<p><strong>C is correct.</strong> The interval is random (changes with each sample), not the parameter.<br>
The true (_1) is fixed but unknown.</p>
</div>
</div>
</div>
</section>
<section id="confidence-intervals-for-other-confidence-levels" class="slide level2">
<h2>Confidence Intervals for Other Confidence Levels</h2>
<p><strong>General formula</strong></p>
<p>[ <em>1 c</em>{/2} (_1). ]</p>
<p><strong>Common choices</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Confidence level</strong></th>
<th style="text-align: right;"><strong>()</strong></th>
<th style="text-align: right;"><strong>Critical value (c_{/2})</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>90%</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">1.645</td>
</tr>
<tr class="even">
<td>95%</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: right;">1.96</td>
</tr>
<tr class="odd">
<td>99%</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">2.58</td>
</tr>
</tbody>
</table>
<p><strong>Tradeoff</strong></p>
<ul>
<li>Higher confidence () wider interval (less precise)</li>
<li>Lower confidence () narrower interval (more precise but less reliable)</li>
</ul>
</section>
<section id="comparing-confidence-levels" class="slide level2">
<h2>Comparing Confidence Levels</h2>

<img src="Lab/figures/ch5_multiple_ci_levels.png" style="width:75.0%" class=" quarto-figure-center"><p class="caption">Comparing confidence levels</p><ul>
<li>Same estimate (_1), but different interval widths</li>
<li>99% CI is widest (most conservative)</li>
<li>90% CI is narrowest (least conservative)</li>
</ul>
</section>
<section id="how-sample-size-affects-precision" class="slide level2">
<h2>How Sample Size Affects Precision</h2>

<img src="Lab/figures/ch5_sample_size_ci.png" style="width:75.0%" class=" quarto-figure-center"><p class="caption">Effect of sample size on CI width</p><p><strong>Key insight:</strong> SE shrinks as (n) increases, making CIs narrower and inference more precise.</p>
</section>
<section id="animated-adding-data-shrinks-the-ci" class="slide level2">
<h2>Animated: Adding Data Shrinks the CI</h2>

<img src="Lab/figures/ch5_ci_animation_1.png" style="width:80.0%" class=" quarto-figure-center"><p class="caption">CI animation frames</p><p><em>(Additional frames can be created as separate slides if desired.)</em></p>
</section>
<section id="confidence-intervals-in-stata" class="slide level2">
<h2>Confidence Intervals in Stata</h2>
<p><strong>Stata automatically reports 95% CIs</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb2-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Example output:</p>
<pre class="text"><code>education | Coef. Std. Err. [95% Conf. Interval]
----------+--------------------------------------------
 | 2.487 0.316 1.868 3.106</code></pre>
<p><strong>Interpretation</strong></p>
<ul>
<li>We are 95% confident that each additional year of education increases wages by between $1.87 and $3.11 per hour.</li>
<li>The interval does not contain 0 () reject (H_0: _1 = 0) at 5% level.</li>
</ul>
</section>
<section id="the-link-between-cis-and-hypothesis-tests" class="slide level2">
<h2>The Link Between CIs and Hypothesis Tests</h2>
<p><strong>Key relationship</strong></p>
<ul>
<li>If (_{1,0}) is <strong>inside</strong> the 95% CI, we <strong>fail to reject</strong> (H_0: <em>1 = </em>{1,0}) at 5% level.</li>
<li>If (_{1,0}) is <strong>outside</strong> the 95% CI, we <strong>reject</strong> (H_0: <em>1 = </em>{1,0}) at 5% level.</li>
</ul>
<p><strong>Example</strong></p>
<ul>
<li>95% CI: ([1.8, 6.6])</li>
<li>(H_0: _1 = 0) () 0 not in CI () reject</li>
<li>(H_0: _1 = 4) () 4 is in CI () fail to reject</li>
</ul>
<p><strong>Takeaway:</strong> CIs provide more information than hypothesis tests—they show a range of plausible values.</p>
</section></section>
<section>
<section id="regression-when-x-is-binary" class="title-slide slide level1 center">
<h1>Regression When (X) is Binary</h1>

</section>
<section id="binary-variables-in-regression" class="slide level2">
<h2>Binary Variables in Regression</h2>
<p>Often, our regressor takes only two values:</p>
<ul>
<li>(X = 1) if small class, (X = 0) if large class</li>
<li>(X = 1) if treated, (X = 0) if control</li>
<li>(X = 1) if college degree, (X = 0) if no degree</li>
<li>(X = 1) if female, (X = 0) if male</li>
</ul>
<p>These are called <strong>binary variables</strong>, <strong>dummy variables</strong>, or <strong>indicator variables</strong>.</p>
<p><strong>Terminology</strong></p>
<ul>
<li>(X = 1): “treatment group” or “category of interest”</li>
<li>(X = 0): “control group” or “reference category”</li>
</ul>
</section>
<section id="what-does-_1-mean-for-binary-x" class="slide level2">
<h2>What Does (_1) Mean for Binary (X)?</h2>
<p>Population regression model:</p>
<p>[ Y_i = _0 + _1 X_i + u_i. ]</p>
<p><strong>When (X_i = 0) (control group):</strong></p>
<p>[ Y_i = _0 + u_i, E[Y_i X_i = 0] = _0. ]</p>
<p><strong>When (X_i = 1) (treatment group):</strong></p>
<p>[ Y_i = _0 + _1 + u_i, E[Y_i X_i = 1] = _0 + _1. ]</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Interpretation of (_1)</strong></p>
</div>
<div class="callout-content">
<p>[ _1 = E[Y_i X_i = 1] - E[Y_i X_i = 0]. ]</p>
<p>(_1) is the <strong>difference in group means</strong>.</p>
</div>
</div>
</div>
</section>
<section id="visualizing-binary-regressors" class="slide level2">
<h2>Visualizing Binary Regressors</h2>

<img src="Lab/figures/ch5_binary_regressor.png" style="width:70.0%" class=" quarto-figure-center"><p class="caption">Binary regressor visualization</p><ul>
<li>(_0): mean of control group ((X = 0))</li>
<li>(_0 + _1): mean of treatment group ((X = 1))</li>
<li>(_1): vertical distance between group means</li>
</ul>
</section>
<section id="example-gender-and-birthweight" class="slide level2">
<h2>Example: Gender and Birthweight</h2>
<p><strong>Research question:</strong> Are male babies heavier than female babies?</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> birthweight male, <span class="kw">robust</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Hypothetical output:</p>
<pre class="text"><code>male | Coef. Std. Err. t P&gt;|t| [95% CI]
------+-----------------------------------------------
 | 2.94 0.81 3.63 0.000 1.35 4.53
_cons | 117.17 0.57 205.56 0.000 116.05 118.29</code></pre>
<p><strong>Interpretation</strong></p>
<ul>
<li>(_0 = 117.17): Average birthweight of <strong>female</strong> babies (male = 0) is 117.17 oz</li>
<li>(_1 = 2.94): Male babies weigh 2.94 oz <strong>more</strong> on average</li>
<li>(t = 3.63) () highly significant ((p &lt; 0.001))</li>
</ul>
</section>
<section id="knowledge-check-binary-regressor-interpretation" class="slide level2">
<h2>Knowledge Check: Binary Regressor Interpretation</h2>
<p><strong>Question</strong></p>
<p>You estimate the effect of a job training program on earnings:</p>
<pre class="text"><code>training | Coef. = 5.2, SE = 1.8, t = 2.89, p = 0.004
_cons | Coef. = 42.3</code></pre>
<p>where <code>training = 1</code> if participated, 0 if not. Earnings in $1000s/year.</p>
<p>What does (_1 = 5.2) mean?</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Answer</strong></p>
</div>
<div class="callout-content">
<p>On average, people who participated in the training program earn <strong>$5,200 more per year</strong> than those who didn’t.<br>
This difference is statistically significant at all conventional levels ((p = 0.004)).</p>
</div>
</div>
</div>
</section>
<section id="binary-regressors-and-randomized-experiments" class="slide level2">
<h2>Binary Regressors and Randomized Experiments</h2>
<p><strong>Special case:</strong> when (X) is randomly assigned (like a clinical trial)</p>
<ul>
<li>Zero conditional mean assumption automatically satisfied</li>
<li>(E[u X] = 0) because treatment is independent of all confounders</li>
<li>(_1) has a <strong>causal interpretation</strong>: the average treatment effect</li>
</ul>
<p><strong>Observational data (no randomization)</strong></p>
<ul>
<li>Must worry about confounders</li>
<li>E.g., college graduates might differ in unobservable ways (ability, motivation)</li>
<li>(_1) captures association, not necessarily causation</li>
</ul>
<p><strong>Takeaway:</strong> Randomization is the gold standard for causal inference.</p>
</section></section>
<section>
<section id="heteroskedasticity-and-homoskedasticity" class="title-slide slide level1 center">
<h1>Heteroskedasticity and Homoskedasticity</h1>

</section>
<section id="what-is-heteroskedasticity" class="slide level2">
<h2>What is Heteroskedasticity?</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Homoskedasticity</strong></p>
</div>
<div class="callout-content">
<p>The variance of the error term is <strong>constant</strong> across all values of (X):</p>
<p>[ (u X = x) = ^2_u x. ]</p>
</div>
</div>
</div>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Heteroskedasticity</strong></p>
</div>
<div class="callout-content">
<p>The variance of the error term <strong>depends on</strong> (X):</p>
<p>[ (u X = x) x. ]</p>
</div>
</div>
</div>
<p>Pronunciation:</p>
<ul>
<li>Homoskedasticity: “homo-sked-ASS-tiss-ity” (constant variance)</li>
<li>Heteroskedasticity: “hetero-sked-ASS-tiss-ity” (varying variance)</li>
</ul>
</section>
<section id="visualizing-homoskedasticity-vs-heteroskedasticity" class="slide level2">
<h2>Visualizing Homoskedasticity vs Heteroskedasticity</h2>

<img src="Lab/figures/ch5_heteroskedasticity.png" style="width:95.0%" class=" quarto-figure-center"><p class="caption">Homoskedastic vs heteroskedastic residuals</p><ul>
<li>Left panel (homoskedastic): residuals have same spread at all (X) values</li>
<li>Right panel (heteroskedastic): residuals fan out as (X) increases</li>
</ul>
</section>
<section id="does-heteroskedasticity-affect-_1" class="slide level2 scrollable">
<h2>Does Heteroskedasticity Affect (_1)?</h2>
<p><strong>Short answer:</strong> <strong>No.</strong></p>
<p>Recall the three least squares assumptions:</p>
<ol type="1">
<li>(E[u X] = 0) (zero conditional mean)</li>
<li>((X_i, Y_i)) are i.i.d.</li>
<li>Large outliers are rare</li>
</ol>
<p>Notice: we never assumed homoskedasticity. Our assumptions <strong>allow</strong> for heteroskedasticity.</p>
<ul>
<li>(_1) is still <strong>unbiased</strong> and <strong>consistent</strong></li>
<li>Point estimates are fine</li>
</ul>
</section>
<section id="so-why-care-about-heteroskedasticity" class="slide level2">
<h2>So Why Care About Heteroskedasticity?</h2>
<p>The problem: heteroskedasticity affects <strong>standard errors</strong>.</p>
<ul>
<li>If errors are homoskedastic, the “textbook” SE formula is correct</li>
<li>If errors are heteroskedastic, that formula is <strong>wrong</strong></li>
<li>Wrong SEs () wrong (t)-statistics () wrong (p)-values () wrong conclusions</li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>The Solution</strong></p>
</div>
<div class="callout-content">
<p>Use <strong>heteroskedasticity-robust standard errors</strong> (also called “robust SEs” or “Huber–White SEs”).<br>
These are valid whether errors are homo- or heteroskedastic.</p>
</div>
</div>
</div>
</section>
<section id="robust-standard-errors-in-stata" class="slide level2">
<h2>Robust Standard Errors in Stata</h2>
<p><strong>Default (homoskedastic SEs – not recommended)</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>With robust SEs (always do this)</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb8-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>What changes:</p>
<ul>
<li>Coefficient estimates: <strong>unchanged</strong></li>
<li>Standard errors: typically change slightly</li>
<li>(t)-statistics and (p)-values: adjusted accordingly</li>
</ul>
</section>
<section id="comparing-homoskedastic-and-robust-ses" class="slide level2">
<h2>Comparing Homoskedastic and Robust SEs</h2>

<img src="Lab/figures/ch5_se_comparison.png" style="width:60.0%" class=" quarto-figure-center"><p class="caption">SE comparison</p><ul>
<li>In this example with heteroskedasticity, robust SE is larger</li>
<li>But this isn’t always the case – it can go either way</li>
<li><strong>Always use robust SEs as a precaution</strong></li>
</ul>
</section>
<section id="heteroskedasticity-the-bottom-line" class="slide level2">
<h2>Heteroskedasticity: The Bottom Line</h2>
<table class="caption-top">
<colgroup>
<col style="width: 50%">
<col style="width: 30%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Situation</strong></th>
<th><strong>Homoskedastic SE</strong></th>
<th><strong>Robust SE</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Errors are homoskedastic</td>
<td>Correct</td>
<td>Correct</td>
</tr>
<tr class="even">
<td>Errors are heteroskedastic</td>
<td>Wrong</td>
<td>Correct</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practical advice</strong></p>
</div>
<div class="callout-content">
<p><strong>Always use robust standard errors.</strong><br>
No downside if errors are homoskedastic, protects you if they’re not.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="the-gaussmarkov-theorem" class="title-slide slide level1 center">
<h1>The Gauss–Markov Theorem</h1>

</section>
<section id="historical-note-when-is-ols-optimal" class="slide level2">
<h2>Historical Note: When is OLS “Optimal”?</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important context</strong></p>
</div>
<div class="callout-content">
<p>This section presents a <strong>theoretical result</strong> that’s mathematically beautiful but has <strong>limited practical relevance</strong> in modern empirical work.</p>
</div>
</div>
</div>
<p>Why learn it anyway?</p>
<ul>
<li>Appears in textbooks and older papers</li>
<li>Helps understand why OLS is the “default” estimator</li>
<li>Shows what assumptions make OLS theoretically optimal</li>
<li>But: we’ve already learned the practical solution (robust SEs)</li>
</ul>
</section>
<section id="when-is-ols-best" class="slide level2 scrollable">
<h2>When is OLS “Best”?</h2>
<p>We know OLS is <strong>unbiased</strong> and <strong>consistent</strong> under the three LS assumptions.</p>
<p><strong>But is it the <em>best</em> estimator we could use?</strong></p>
<p>The Gauss–Markov theorem answers this under a <strong>fourth assumption</strong>.</p>
<p><strong>Extended LS assumptions (four total)</strong>:</p>
<ol type="1">
<li>(E[u X] = 0)</li>
<li>((X_i, Y_i)) are i.i.d.</li>
<li>Large outliers are rare</li>
<li>(u) is <strong>homoskedastic</strong></li>
</ol>
</section>
<section id="the-gaussmarkov-theorem-1" class="slide level2">
<h2>The Gauss–Markov Theorem</h2>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Gauss–Markov Theorem</strong></p>
</div>
<div class="callout-content">
<p>Under the four extended least squares assumptions, (_1) has the <strong>smallest variance</strong> among all <strong>linear unbiased estimators</strong>.</p>
</div>
</div>
</div>
<p>This makes OLS <strong>BLUE</strong>:</p>
<ul>
<li><strong>B</strong>est (minimum variance)</li>
<li><strong>L</strong>inear (estimator is a linear function of (Y_1, , Y_n))</li>
<li><strong>U</strong>nbiased ((E[_1] = _1))</li>
<li><strong>E</strong>stimator</li>
</ul>
</section>
<section id="what-blue-means-and-doesnt-mean" class="slide level2">
<h2>What BLUE Means (and Doesn’t Mean)</h2>
<p><strong>BLUE means</strong></p>
<ul>
<li>Among all linear unbiased estimators, OLS is most precise (smallest ((_1)))</li>
<li>Under homoskedasticity, you can’t do better with a linear estimator</li>
</ul>
<p><strong>BLUE does <em>not</em> mean</strong></p>
<ul>
<li>OLS is best among <strong>all</strong> estimators (only linear ones)</li>
<li>OLS is best when errors are heteroskedastic (theorem requires homoskedasticity)</li>
<li>OLS is unbiased without the zero conditional mean assumption (still need assumption 1)</li>
</ul>
</section>
<section id="limitations-of-the-gaussmarkov-theorem" class="slide level2 scrollable">
<h2>Limitations of the Gauss–Markov Theorem</h2>
<p>Why we don’t rely heavily on it:</p>
<ol type="1">
<li><strong>Homoskedasticity is rare in practice</strong>
<ul>
<li>Real-world data almost always exhibit some heteroskedasticity</li>
<li>The theorem doesn’t apply</li>
</ul></li>
<li><strong>Restricted to linear estimators</strong>
<ul>
<li>Many better nonlinear estimators exist</li>
<li>E.g., weighted least squares (if we know form of heteroskedasticity)</li>
<li>E.g., least absolute deviations (robust to outliers)</li>
</ul></li>
</ol>
<p><strong>Takeaway:</strong> OLS is a good default, but not always optimal.</p>
</section>
<section id="gaussmarkov-the-practical-bottom-line" class="slide level2">
<h2>Gauss–Markov: The Practical Bottom Line</h2>
<p>What you need to remember:</p>
<ul>
<li>Gauss–Markov says OLS is BLUE <strong>under homoskedasticity</strong></li>
<li>But homoskedasticity rarely holds in practice</li>
<li><strong>Modern solution:</strong> use OLS with <strong>robust standard errors</strong>
<ul>
<li>Point estimates (_1): unchanged</li>
<li>Standard errors: corrected for heteroskedasticity</li>
<li>Inference: valid whether or not errors are homoskedastic</li>
</ul></li>
</ul>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Practical advice</strong></p>
</div>
<div class="callout-content">
<p>Don’t worry too much about whether errors are homoskedastic.<br>
Just always use <code>, robust</code> in Stata.</p>
</div>
</div>
</div>
</section>
<section id="why-we-still-use-ols" class="slide level2">
<h2>Why We Still Use OLS</h2>
<p>Despite limitations, OLS is the workhorse of econometrics:</p>
<ul>
<li><strong>Simplicity:</strong> easy to compute and interpret</li>
<li><strong>Robustness:</strong> works reasonably well under a wide variety of conditions</li>
<li><strong>Robust SEs:</strong> fix the heteroskedasticity problem for inference</li>
<li><strong>Familiarity:</strong> everyone knows how to interpret regression output</li>
<li><strong>Unbiased under weak assumptions:</strong> just need (E[u X] = 0), i.i.d., no huge outliers</li>
</ul>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Modern practice</strong></p>
</div>
<div class="callout-content">
<p>Use OLS with <strong>robust standard errors</strong> as your baseline.<br>
Consider alternatives (WLS, LAD, etc.) only when you have specific concerns.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="implementing-inference-in-stata" class="title-slide slide level1 center">
<h1>Implementing Inference in Stata</h1>

</section>
<section id="complete-stata-workflow" class="slide level2">
<h2>Complete Stata Workflow</h2>
<p><strong>1. Load data and explore</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> <span class="st">"data.dta"</span>, <span class="kw">clear</span></span>
<span id="cb9-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">summarize</span> wage education</span>
<span id="cb9-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">scatter</span> wage education</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>2. Run regression with robust SEs</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb10-1"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p><strong>3. Interpret output</strong></p>
<ul>
<li>Coefficient: effect size</li>
<li>(t)-statistic: evidence against (H_0: _1 = 0)</li>
<li>(p)-value: significance level</li>
<li>95% CI: range of plausible values</li>
</ul>
</section>
<section id="manual-calculations-in-stata" class="slide level2">
<h2>Manual Calculations in Stata</h2>
<p><strong>Extract regression results and compute manually</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="" aria-hidden="true" tabindex="-1"></a>* Run regression</span>
<span id="cb11-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span>
<span id="cb11-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="" aria-hidden="true" tabindex="-1"></a>* Extract coefficient and <span class="kw">SE</span></span>
<span id="cb11-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> beta1_hat = _b[education]</span>
<span id="cb11-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> se_beta1 = _se[education]</span>
<span id="cb11-7"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="" aria-hidden="true" tabindex="-1"></a>* Test H0: beta1 = 0</span>
<span id="cb11-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> t_stat = beta1_hat / se_beta1</span>
<span id="cb11-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> p_value = 2 * (1 - <span class="fu">normal</span>(<span class="fu">abs</span>(t_stat)))</span>
<span id="cb11-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="" aria-hidden="true" tabindex="-1"></a>* Display results</span>
<span id="cb11-13"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"Coefficient: "</span> beta1_hat</span>
<span id="cb11-14"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"Standard Error: "</span> se_beta1</span>
<span id="cb11-15"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"t-statistic: "</span> t_stat</span>
<span id="cb11-16"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"p-value: "</span> p_value</span>
<span id="cb11-17"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="" aria-hidden="true" tabindex="-1"></a>* 95% Confidence Interval</span>
<span id="cb11-19"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> ci_lower = beta1_hat - 1.96 * se_beta1</span>
<span id="cb11-20"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> ci_upper = beta1_hat + 1.96 * se_beta1</span>
<span id="cb11-21"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"95% CI: ["</span> ci_lower <span class="st">", "</span> ci_upper <span class="st">"]"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Full walkthrough script: <code>econ3500_inference_walkthrough.do</code>.</p>
</section>
<section id="testing-non-zero-null-hypotheses-in-stata" class="slide level2">
<h2>Testing Non-Zero Null Hypotheses in Stata</h2>
<p>**Test (H_0: _1 = 3) vs (H_1: _1 )**</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb12-1"><a href="" aria-hidden="true" tabindex="-1"></a>* Run regression</span>
<span id="cb12-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span>
<span id="cb12-3"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="" aria-hidden="true" tabindex="-1"></a>* Compute t-statistic <span class="kw">for</span> H0: beta1 = 3</span>
<span id="cb12-5"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> beta1_0 = 3</span>
<span id="cb12-6"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> t_custom = (_b[education] - beta1_0) / _se[education]</span>
<span id="cb12-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> p_custom = 2 * (1 - <span class="fu">normal</span>(<span class="fu">abs</span>(t_custom)))</span>
<span id="cb12-8"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"t-statistic for H0: beta1 = 3: "</span> t_custom</span>
<span id="cb12-10"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">display</span> <span class="st">"p-value: "</span> p_custom</span>
<span id="cb12-11"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="" aria-hidden="true" tabindex="-1"></a>* Decision</span>
<span id="cb12-13"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">if</span> <span class="fu">abs</span>(t_custom) &gt; 1.96 {</span>
<span id="cb12-14"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="kw">display</span> <span class="st">"Reject H0 at 5% level"</span></span>
<span id="cb12-15"><a href="" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-16"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">else</span> {</span>
<span id="cb12-17"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="kw">display</span> <span class="st">"Fail to reject H0 at 5% level"</span></span>
<span id="cb12-18"><a href="" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="checking-for-heteroskedasticity-visual" class="slide level2">
<h2>Checking for Heteroskedasticity (Visual)</h2>
<p><strong>Residual plot to diagnose heteroskedasticity</strong></p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="" aria-hidden="true" tabindex="-1"></a>* Run regression and <span class="fu">get</span> residuals</span>
<span id="cb13-2"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">regress</span> wage education, <span class="kw">robust</span></span>
<span id="cb13-3"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> wage_fitted, <span class="kw">xb</span></span>
<span id="cb13-4"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> residual, residuals</span>
<span id="cb13-5"><a href="" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="" aria-hidden="true" tabindex="-1"></a>* Residual plot</span>
<span id="cb13-7"><a href="" aria-hidden="true" tabindex="-1"></a><span class="kw">scatter</span> residual wage_fitted, <span class="co">///</span></span>
<span id="cb13-8"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="kw">yline</span>(0) <span class="co">///</span></span>
<span id="cb13-9"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="bn">title</span>(<span class="st">"Residual Plot"</span>) <span class="co">///</span></span>
<span id="cb13-10"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="bn">xtitle</span>(<span class="st">"Fitted Values"</span>) <span class="co">///</span></span>
<span id="cb13-11"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="bn">ytitle</span>(<span class="st">"Residuals"</span>) <span class="co">///</span></span>
<span id="cb13-12"><a href="" aria-hidden="true" tabindex="-1"></a> <span class="kw">note</span>(<span class="st">"Funnel shape suggests heteroskedasticity"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>What to look for:</p>
<ul>
<li>Constant spread () homoskedastic</li>
<li>Funnel/cone shape () heteroskedastic</li>
<li>Either way, use robust SEs</li>
</ul>
</section></section>
<section>
<section id="bringing-it-all-together" class="title-slide slide level1 center">
<h1>Bringing It All Together</h1>

</section>
<section id="the-inference-workflow" class="slide level2 scrollable">
<h2>The Inference Workflow</h2>
<ol type="1">
<li><strong>Estimate</strong> the model: (_1 (_1))</li>
<li><strong>Test</strong> hypotheses: compute (t = )</li>
<li><strong>Make decision:</strong> reject if (|t| &gt; c_{/2}) or (p)-value &lt; ()</li>
<li><strong>Construct CI:</strong> (<em>1 c</em>{/2} (_1))</li>
<li><strong>Interpret:</strong> economic significance, not just statistical</li>
<li><strong>Always use robust SEs</strong> to account for potential heteroskedasticity</li>
</ol>
</section>
<section id="key-formulas-summary" class="slide level2">
<h2>Key Formulas Summary</h2>
<table class="caption-top">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Concept</strong></th>
<th><strong>Formula</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(t)-statistic</td>
<td>(t = (<em>1 - </em>{1,0}) / (_1))</td>
</tr>
<tr class="even">
<td>95% confidence interval</td>
<td>(_1 (_1))</td>
</tr>
<tr class="odd">
<td>Binary regressor interpretation</td>
<td>(_1 = E[Y X=1] - E[Y X=0])</td>
</tr>
<tr class="even">
<td>Rejection region (two-tailed, 5%)</td>
<td>(</td>
</tr>
<tr class="odd">
<td>Rejection region (one-tailed, 5%)</td>
<td>(t &gt; 1.645) or (t &lt; -1.645)</td>
</tr>
</tbody>
</table>
</section>
<section id="common-mistakes-to-avoid" class="slide level2 scrollable">
<h2>Common Mistakes to Avoid</h2>
<ol type="1">
<li><strong>Using homoskedastic SEs instead of robust</strong>
<ul>
<li>Always add <code>, robust</code> in Stata.</li>
</ul></li>
<li><strong>Confusing statistical and economic significance</strong>
<ul>
<li>Check both the (p)-value <strong>and</strong> the magnitude.</li>
</ul></li>
<li><strong>Misinterpreting confidence intervals</strong>
<ul>
<li>The interval is random, not the parameter.</li>
<li>“95% confident” () “95% probability”.</li>
</ul></li>
<li><strong>Forgetting that binary regressors are differences in means</strong>
<ul>
<li>For a binary regressor, (_1) is a difference in group means.</li>
</ul></li>
<li><strong>Thinking BLUE applies with heteroskedasticity</strong>
<ul>
<li>Gauss–Markov requires homoskedasticity.</li>
</ul></li>
</ol>
</section>
<section id="final-knowledge-check-putting-it-together" class="slide level2 scrollable">
<h2>Final Knowledge Check: Putting It Together</h2>
<p><strong>Comprehensive problem</strong></p>
<p>You estimate the effect of small class sizes (binary: 1 = small, 0 = regular) on test scores:</p>
<pre class="text"><code>small_class | Coef. = 12.3, SE = 3.8, p = 0.001
_cons | Coef. = 78.5
n = 300, R² = 0.15</code></pre>
<p>Questions:</p>
<ol type="1">
<li>What is the average test score in regular classes?</li>
<li>What is the effect of small classes? Is it significant?</li>
<li>Construct a 95% CI for the effect.</li>
<li>If you tested (H_0): small classes increase scores by 15 points, what would you conclude?</li>
</ol>
</section>
<section id="final-knowledge-check-answers" class="slide level2 scrollable">
<h2>Final Knowledge Check: Answers</h2>
<ol type="1">
<li><p><strong>Regular class average:</strong> (_0 = 78.5) points.</p></li>
<li><p><strong>Small class effect:</strong> students in small classes score 12.3 points higher on average. This is highly significant ((p = 0.001 &lt; 0.05)).</p></li>
<li><p><strong>95% CI:</strong> (12.3 (3.8) = [4.85, 19.75]). We are 95% confident the true effect is between 4.85 and 19.75 points.</p></li>
<li><p>**Test (H_0: _1 = 15):**</p>
<p>[ t = = -0.71. ]</p>
<p>Since (|-0.71| &lt; 1.96), <strong>fail to reject</strong>. The data are consistent with an effect of 15 points (even though our point estimate is 12.3).</p></li>
</ol>
</section>
<section id="looking-ahead" class="slide level2">
<h2>Looking Ahead</h2>
<p>What we’ve learned:</p>
<ul>
<li>How to quantify uncertainty with SEs and CIs</li>
<li>How to test whether relationships are “real” or just noise</li>
<li>How to handle binary variables and heteroskedasticity</li>
</ul>
<p><strong>Next chapter: Multiple regression</strong></p>
<ul>
<li>What if we want to control for multiple factors simultaneously?</li>
<li>How do we interpret coefficients with many regressors?</li>
<li>Omitted variable bias revisited</li>
</ul>
<p><strong>Suggestion:</strong> Practice the Stata walkthrough to solidify these concepts.</p>

</section></section>
 </div>
 <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>ECON3500 | Hypothesis Tests and Confidence Intervals</p>
</div>
</div></div>

 <script>window.backupDefine = window.define; window.define = undefined;</script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/dist/reveal.js"></script>
 <!-- reveal.js plugins -->
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/quarto-support/support.js"></script>
 

 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/notes/notes.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/search/search.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/zoom/zoom.js"></script>
 <script src="ch5_hypothesis_tests_new_files/libs/revealjs/plugin/math/math.js"></script>
 <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

 <script>

 // Full list of configuration options available at:
 // https://revealjs.com/config/
 Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'pdfMaxPagesPerSlide': 1,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
 // Display controls in the bottom right corner
 controls: false,

 // Help the user learn the controls by providing hints, for example by
 // bouncing the down arrow when they first encounter a vertical slide
 controlsTutorial: false,

 // Determines where controls appear, "edges" or "bottom-right"
 controlsLayout: 'edges',

 // Visibility rule for backwards navigation arrows; "faded", "hidden"
 // or "visible"
 controlsBackArrows: 'faded',

 // Display a presentation progress bar
 progress: true,

 // Display the page number of the current slide
 slideNumber: 'c/t',

 // 'all', 'print', or 'speaker'
 showSlideNumber: 'all',

 // Add the current slide number to the URL hash so that reloading the
 // page/copying the URL will return you to the same slide
 hash: true,

 // Start with 1 for the hash rather than 0
 hashOneBasedIndex: false,

 // Flags if we should monitor the hash and change slides accordingly
 respondToHashChanges: true,

 // Push each slide change to the browser history
 history: true,

 // Enable keyboard shortcuts for navigation
 keyboard: true,

 // Enable the slide overview mode
 overview: true,

 // Disables the default reveal.js slide layout (scaling and centering)
 // so that you can use custom CSS layout
 disableLayout: false,

 // Vertical centering of slides
 center: false,

 // Enables touch navigation on devices with touch input
 touch: true,

 // Loop the presentation
 loop: false,

 // Change the presentation direction to be RTL
 rtl: false,

 // see https://revealjs.com/vertical-slides/#navigation-mode
 navigationMode: 'linear',

 // Randomizes the order of slides each time the presentation loads
 shuffle: false,

 // Turns fragments on and off globally
 fragments: true,

 // Flags whether to include the current fragment in the URL,
 // so that reloading brings you to the same fragment position
 fragmentInURL: false,

 // Flags if the presentation is running in an embedded mode,
 // i.e. contained within a limited portion of the screen
 embedded: false,

 // Flags if we should show a help overlay when the questionmark
 // key is pressed
 help: true,

 // Flags if it should be possible to pause the presentation (blackout)
 pause: true,

 // Flags if speaker notes should be visible to all viewers
 showNotes: false,

 // Global override for autoplaying embedded media (null/true/false)
 autoPlayMedia: null,

 // Global override for preloading lazy-loaded iframes (null/true/false)
 preloadIframes: null,

 // Number of milliseconds between automatically proceeding to the
 // next slide, disabled when set to 0, this value can be overwritten
 // by using a data-autoslide attribute on your slides
 autoSlide: 0,

 // Stop auto-sliding after user input
 autoSlideStoppable: true,

 // Use this method for navigation when auto-sliding
 autoSlideMethod: null,

 // Specify the average time in seconds that you think you will spend
 // presenting each slide. This is used to show a pacing timer in the
 // speaker view
 defaultTiming: null,

 // Enable slide navigation via mouse wheel
 mouseWheel: false,

 // The display mode that will be used to show slides
 display: 'block',

 // Hide cursor if inactive
 hideInactiveCursor: true,

 // Time before the cursor is hidden (in ms)
 hideCursorTime: 5000,

 // Opens links in an iframe preview overlay
 previewLinks: false,

 // Transition style (none/fade/slide/convex/concave/zoom)
 transition: 'fade',

 // Transition speed (default/fast/slow)
 transitionSpeed: 'default',

 // Transition style for full page slide backgrounds
 // (none/fade/slide/convex/concave/zoom)
 backgroundTransition: 'fade',

 // Number of slides away from the current that are visible
 viewDistance: 3,

 // Number of slides away from the current that are visible on mobile
 // devices. It is advisable to set this to a lower number than
 // viewDistance in order to save resources.
 mobileViewDistance: 2,

 // The "normal" size of the presentation, aspect ratio will be preserved
 // when the presentation is scaled to fit different resolutions. Can be
 // specified using percentage units.
 width: 1280,

 height: 720,

 // Factor of the display size that should remain empty around the content
 margin: 0.1,

 math: {
 mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
 config: 'TeX-AMS_HTML-full',
 tex2jax: {
 inlineMath: [['\\(','\\)']],
 displayMath: [['\\[','\\]']],
 balanceBraces: true,
 processEscapes: false,
 processRefs: true,
 processEnvironments: true,
 preview: 'TeX',
 skipTags: ['script','noscript','style','textarea','pre','code'],
 ignoreClass: 'tex2jax_ignore',
 processClass: 'tex2jax_process'
 },
 },

 // reveal.js plugins
 plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

 RevealMath,
 RevealNotes,
 RevealSearch,
 RevealZoom
 ]
 });
 </script>
 <script>
 (function () {
 function ensureSrc() {
 document.querySelectorAll("img[data-src]").forEach(function (img) {
 if (!img.getAttribute("src")) {
 img.setAttribute("src", img.getAttribute("data-src"));
 }
 });
 document.querySelectorAll("source[data-src]").forEach(function (source) {
 if (!source.getAttribute("src")) {
 source.setAttribute("src", source.getAttribute("data-src"));
 }
 });
 }

 function relayout() {
 if (window.Reveal && typeof window.Reveal.layout === "function") {
 window.Reveal.layout();
 }
 }

 function hookReveal() {
 if (window.Reveal && typeof window.Reveal.on === "function") {
 window.Reveal.on("ready", function () {
 ensureSrc();
 relayout();
 });
 window.Reveal.on("slidechanged", relayout);
 window.Reveal.on("overviewshown", function () {
 ensureSrc();
 relayout();
 });
 window.Reveal.on("overviewhidden", relayout);
 return true;
 }
 return false;
 }

 document.addEventListener("DOMContentLoaded", function () {
 ensureSrc();
 relayout();

 var imgs = document.querySelectorAll(".reveal img");
 var pending = 0;
 imgs.forEach(function (img) {
 if (!img.complete) {
 pending += 1;
 img.addEventListener(
 "load",
 function () {
 pending -= 1;
 if (pending === 0) {
 relayout();
 }
 },
 { once: true }
 );
 }
 });
 if (pending === 0) {
 relayout();
 }
 });

 window.addEventListener("load", relayout);

 if (!hookReveal()) {
 var tries = 0;
 var t = window.setInterval(function () {
 tries += 1;
 if (hookReveal() || tries > 20) {
 window.clearInterval(t);
 }
 }, 250);
 }
 })();
 </script>
 <script id="quarto-html-after-body" type="application/javascript">
 window.document.addEventListener("DOMContentLoaded", function (event) {
 const tabsets = window.document.querySelectorAll(".panel-tabset-tabby")
 tabsets.forEach(function(tabset) {
 const tabby = new Tabby('#' + tabset.id);
 });
 const isCodeAnnotation = (el) => {
 for (const clz of el.classList) {
 if (clz.startsWith('code-annotation-')) { 
 return true;
 }
 }
 return false;
 }
 const onCopySuccess = function(e) {
 // button target
 const button = e.trigger;
 // don't keep focus
 button.blur();
 // flash "checked"
 button.classList.add('code-copy-button-checked');
 var currentTitle = button.getAttribute("title");
 button.setAttribute("title", "Copied!");
 let tooltip;
 if (window.bootstrap) {
 button.setAttribute("data-bs-toggle", "tooltip");
 button.setAttribute("data-bs-placement", "left");
 button.setAttribute("data-bs-title", "Copied!");
 tooltip = new bootstrap.Tooltip(button, 
 { trigger: "manual", 
 customClass: "code-copy-button-tooltip",
 offset: [0, -8]});
 tooltip.show(); 
 }
 setTimeout(function() {
 if (tooltip) {
 tooltip.hide();
 button.removeAttribute("data-bs-title");
 button.removeAttribute("data-bs-toggle");
 button.removeAttribute("data-bs-placement");
 }
 button.setAttribute("title", currentTitle);
 button.classList.remove('code-copy-button-checked');
 }, 1000);
 // clear code selection
 e.clearSelection();
 }
 const getTextToCopy = function(trigger) {
 const outerScaffold = trigger.parentElement.cloneNode(true);
 const codeEl = outerScaffold.querySelector('code');
 for (const childEl of codeEl.children) {
 if (isCodeAnnotation(childEl)) {
 childEl.remove();
 }
 }
 return codeEl.innerText;
 }
 const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
 text: getTextToCopy
 });
 clipboard.on('success', onCopySuccess);
 if (window.document.getElementById('quarto-embedded-source-code-modal')) {
 const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
 text: getTextToCopy,
 container: window.document.getElementById('quarto-embedded-source-code-modal')
 });
 clipboardModal.on('success', onCopySuccess);
 }
 var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
 var mailtoRegex = new RegExp(/^mailto:/);
 var filterRegex = new RegExp('/' + window.location.host + '/');
 var isInternal = (href) => {
 return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
 }
 // Inspect non-navigation links and adorn them if external
 var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
 for (var i=0; i<links.length; i++) {
 const link = links[i];
 if (!isInternal(link.href)) {
 // undo the damage that might have been done by quarto-nav.js in the case of
 // links that we want to consider external
 if (link.dataset.originalHref !== undefined) {
 link.href = link.dataset.originalHref;
 }
 }
 }
 function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
 const config = {
 allowHTML: true,
 maxWidth: 500,
 delay: 100,
 arrow: false,
 appendTo: function(el) {
 return el.closest('section.slide') || el.parentElement;
 },
 interactive: true,
 interactiveBorder: 10,
 theme: 'light-border',
 placement: 'bottom-start',
 };
 if (contentFn) {
 config.content = contentFn;
 }
 if (onTriggerFn) {
 config.onTrigger = onTriggerFn;
 }
 if (onUntriggerFn) {
 config.onUntrigger = onUntriggerFn;
 }
 config['offset'] = [0,0];
 config['maxWidth'] = 700;
 window.tippy(el, config); 
 }
 const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
 for (var i=0; i<noterefs.length; i++) {
 const ref = noterefs[i];
 tippyHover(ref, function() {
 // use id or data attribute instead here
 let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
 try { href = new URL(href).hash; } catch {}
 const id = href.replace(/^#\/?/, "");
 const note = window.document.getElementById(id);
 if (note) {
 return note.innerHTML;
 } else {
 return "";
 }
 });
 }
 const findCites = (el) => {
 const parentEl = el.parentElement;
 if (parentEl) {
 const cites = parentEl.dataset.cites;
 if (cites) {
 return {
 el,
 cites: cites.split(' ')
 };
 } else {
 return findCites(el.parentElement)
 }
 } else {
 return undefined;
 }
 };
 var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
 for (var i=0; i<bibliorefs.length; i++) {
 const ref = bibliorefs[i];
 const citeInfo = findCites(ref);
 if (citeInfo) {
 tippyHover(citeInfo.el, function() {
 var popup = window.document.createElement('div');
 citeInfo.cites.forEach(function(cite) {
 var citeDiv = window.document.createElement('div');
 citeDiv.classList.add('hanging-indent');
 citeDiv.classList.add('csl-entry');
 var biblioDiv = window.document.getElementById('ref-' + cite);
 if (biblioDiv) {
 citeDiv.innerHTML = biblioDiv.innerHTML;
 }
 popup.appendChild(citeDiv);
 });
 return popup.innerHTML;
 });
 }
 }
 });
 </script>
 

</body></html>