---
title: "General problems you could face this semester"
sitetitle: I have a problem
summary: Sometimes you get sick. Or awful things happen. You’re not alone, and UVM has support for you.

date: "2026-01-06"

menu:
  resources:
    parent: Resources
    weight: 1
  
  # Academic page type (do not modify).
type: docs
output:
  blogdown::html_page:
    toc: true
---
Sometimes you get sick. Or awful things happen. You’re not alone, and UVM has support for you.^[I collaborated on this guide with UVM English professors Holly Painter and Susanmarie Harrington. This stuff is generally true for all of your classes. Everyone here wants you to succeed.] 

# Problems 

## Health, family, and friends 
### I’m not feeling well

Stay home! Rest. Help your body help you. 

In the meantime, you can complete a [Short-Term Acute Illness Form](https://forms.office.com/pages/responsepage.aspx?id=WHcXHGtN3EOq6zucQlYpZ5YlvVi7m2FOggf-Zh_-E_RUMDcyT0paSlo0SkkwS0hMUFpHSjY1QlhLMyQlQCN0PWcu&route=shorturl). This will alert Student Services about what's going on, and they will reach out to all your professors at once. Then, your professors can make accommodations to help you. You can reach out to me directly as well or wait for the form to go through.. 

You can also schedule an appointment at [Student Health Services](https://www.uvm.edu/health/) (802-656-3350). 


### Something big is wrong - I have a serious illness or injury 

If your health problem goes beyond "short-term acute illness," please reach out to [Student Services](#studentservices) at your college. They will help you! It is their job.

### I’m experiencing a family emergency
Same as above. Reach out to your college’s [Student Services](#studentservices) office. They’re here to help you.

### I’m struggling with my mental health 

Mental health problems are health problems. If you're struggling and your mental health is affecting your school performance, your college’s [Student Services](#studentservices) office can help you arrange accommodations with your professors. This is very common! 

Please consider reaching out to [Counseling and Psychiatry Services (CAPS)](https://www.uvm.edu/health) (802-656-3340). They are free and confidential, though there may be a wait for the first appointment. If you need a same-day appointment, tell them, and they will help you right away. 

### I’m experiencing food/housing insecurity
If you are facing problems securing food or housing, I strongly encourage you to contact your college’s [Student Services](#studentservices) office. You can also talk to me if you feel comfortable. UVM also has [several initiatives](https://www.uvm.edu/health/food-insecurity-uvm) to help with food insecurity. This includes the Rally Cat Cupboard on the first floor of the Davis Center.

### I’m worried about a friend
Call the [Dean of Students Office](https://www.uvm.edu/deanofstudents) (802-656-3380). If you’d like to stay anonymous, you can submit a [C.A.R.E. form online](https://www.uvm.edu/deanofstudents/student_advocacy/care_form) and the C.A.R.E. team will follow up with your friend. If it’s an emergency, call 911 off campus or 802-656-3473 on campus. 


## Someone has discriminated against me or harassed me because of my identity

This is not okay, and it’s a violation of UVM policy. You can [file a
report](https://cm.maxient.com/reportingform.php?UnivofVermont&layout_id=35),
which will be investigated by the Office of Equal Opportunity.

## I’ve witnessed a crime or I’m being threatened

If there is a crime in progress or an emergency situation, call 911 or UVM Police Services at 802-656-3473. To report a crime after the fact,
use the [CATSafe app](https://www.uvm.edu/dsc/catsafe) or [this form**](https://forms.office.com/pages/responsepage.aspx?id=WHcXHGtN3EOq6zucQlYpZ-G8bUjYdfdBoog7_xbTVPJUNEtMNkhVMlBITDk1VzY4SEQ4Q1k4MlZIUC4u&route=shorturl).
Refer to [this webpage](https://www.uvm.edu/dsc/threat-recognition-and-reporting) for information about reporting threats.

## Someone has sexually assaulted or harassed me

This is not your fault, and there is help available to you in the coming days, weeks, and months.
UVM’s physical and mental health resources are coordinated through the [Center for Health & Wellbeing](https://www.uvm.edu/health). You can get completely confidential help through [Hope Works](https://hopeworksvt.org/) (call 802-863-1236 or visit their [website](https://hopeworksvt.org/) to contact an advocate or therapist, or their 24-hour chat line).

You don’t need to report assault or harassment to access medical or support services, but if you decide to report it, you can do so anytime. To file a criminal report, contact [UVM Police](https://www.uvm.edu/police) (802-656-3473). To start an internal (non-criminal) investigation of harassment, use this [form](https://cm.maxient.com/reportingform.php?UnivofVermont&layout_id=35).

Please note that most UVM faculty and staff (professors, advisors, Res Life staff, student employee supervisors, etc.) are mandated reporters, meaning that, if you write about or tell us about a sexual assault or sexual harassment, we’re **required** to report it to UVM’s Title IX Coordinator. (This is not the case for [Hope Works](https://hopeworksvt.org/).) But you never need to disclose details about assault or harassment in order to ask questions about how to get support.


## I’m falling behind academically
Come to office hours or  e-mail me so we can find a time to talk!

<!-- The Tutoring Center offers free tutoring in learning skills, subject area tutoring, and supplemental instruction. -->

The [Undergraduate Writing Center provides](https://www.uvm.edu/undergradwriting) free writing support and feedback at any point in the writing process for any class and any type of assignment. 


The books and research databases at [Howe Library](http://library.uvm.edu/) are invaluable resources. If you need research help in any course, [UVM research librarians](https://libraries.uvm.edu/services/research-support) are at the ready.

If you have a documented disability and you’re interested in utilizing accommodations, contact [Student Accessibility Services](https://www.uvm.edu/academicsuccess/student_accessibility_services). You’re also strongly encouraged to discuss with your professors the accommodations you plan to use in each course. 


## My computer is broken
UVM’s [Enterprise Technology Services](https://www.uvm.edu/it/help-and-support) offers free software support and can also do (not-free) repairs on Apple and Dell computers. Off-campus, [Small Dog Electronics](https://smalldog.com/pages/service) does repairs on PCs, Macs, iPhones, and iPads.


# Student Services {#studentservices .unnumbered}
For many of these situations, your first contact will be Student Services in your college:

| | |
|---|---|
|[CALS (Agriculture & Life Sciences)](https://www.uvm.edu/cals/student-services) <br>email: calsstudentservices@uvm.edu	|		[CAS (Arts & Sciences)](https://www.uvm.edu/cas/student-services) <br>	email: cas@uvm.edu 		|
[CEMS (Engineering & Mathematical Sciences)](https://www.uvm.edu/cems/cems-student-services) <br>	email: cems.student.services@uvm.edu	|	[CESS (Education & Social Services)](https://www.uvm.edu/cess/cess-undergraduate-student-services) <br>		email: cessstsv@uvm.edu|
[CNHS (Nursing & Health Sciences)](https://www.uvm.edu/cnhs/advising) <br>	email: cnhs@uvm.edu			|		[Rubenstein (Environment / Nat. Resources)](https://www.uvm.edu/rsenr/student-services) <br> 		email: marie.vea@uvm.edu (Asst. Dean)|
[Grossman (Business)](https://www.uvm.edu/business/center-student-success) <br> email: gsbcss@uvm.edu|

