---
title: "Research Paper: Data Abstract"
linktitle: "03 Data Abstract"
date: "2023-08-26"
due_date: "2020-10-26"
due_time: "11:59 PM"
menu:
  assignment:
    parent: Research Paper
    weight: 4
type: docs
editor_options: 
  chunk_output_type: console
---

## Objective {#objective .unnumbered}

The goal of this submission is to help you front-load finding and
setting up the data set(s) you need for your analysis, so that you have
all the information you need to develop a careful empirical strategy and
analysis plan for your paper (and paper proposal).

## Components {#components .unnumbered}

The data abstract should consist of two things:

1.  A write-up (roughly one page) of your chosen research question. It
    should clearly state your research question, discuss the data sets
    you will include, and list the variables from those data sets you
    plan to include. Think of this taking one of your ideas from your
    idea proposal, revising it to reflect any feedback, and adding
    specifics about the data and variables you will use in your
    analysis.

    1.  Your research question should be clearly stated, and it should
        be answerable with the data you describe.

    2.  Be clear about everything we need to know regarding your data.
        Where is it from? What years are available? What
        countries/groups are included?

    3.  Be specific about what variables you will include in your
        analysis. These variables should be summarized in your summary
        statistics table. If you weren't able to get all of them up and
        running, discuss what additional variables you plan to add and
        where you will get them from.

    4.  Ultimately, any data sets you use will need to be cited in your
        references/bibliography section, so include those citations at
        the bottom of your document as well.

2.  A "summary statistics" table that includes the basic descriptive
    statistics that will be relevant to your analysis. Ultimately, this
    table will probably be the first table in your final paper. It
    should be **formatted nicely** (i.e., not copied directly out of Stata)
    with easy-to-interpret variables names and column headers, and it
    will likely include the following:

    -   Number of observations

    -   Means and standard deviations of your dependent variable(s)

    -   Means and standard deviations of your key independent
        variable(s)

    -   If you are comparing two (or more) groups, you will likely want
        to report means separately for each group.

    -   Any other details that might be relevant to your data (i.e.
        number of states, number of years, number of households, etc.)

    **Consult the [grading rubric](#rubric) for additional guidance!**

## Submission requirements {#submission-requirements .unnumbered}

Submit to me the following through Blackboard (submissions folder)

-   Data abstract (in Word or as a PDF) - write-up + summary table

-   Do-file that imports your data set(s) and creates your results

-   Log file


## Rubric {#rubric .unnumbered}


You will be graded on the following  criteria for each question, 22 points total 

||  	Does not meet (0 points) |	Partially meets (1 points) |	Fully meets (2 points)|
|:--|:---|:---|:---|
|Research question  |	Research question is absent or too broad to interpret 	| 	Research question is stated but not specific and/or not answerable 	| 	Research question is clearly stated, specific, and answerable|
|Data set (points x 3) |	Data set not listed or completely inappropriate to answer research question 	|	Data set(s) listed, but may be insufficient to answer question 	|	Data set(s) that will be used are clearly identified, appropriate to answer question
|Data files | 	No evidence of data files in Stata 	 |	Data files imported into Stata, with some problems | 	Data files imported into Stata successfully|
|Data table (points x 3) |	Table missing, or irrelevant to analysis 	 |	Table appropriately summarizes few independent variables 	 |	Table appropriately summarizes dependent and key independent variables|
|Formatting| Summary statistics table is unformatted, making interpretation difficult 	|Summary statistics table is sloppy and/or copied/pasted out of Stata 	|Summary statistics table is clearly formatted and easy to read|
|Do-file|Do-file missing 	|Partial do-file, or complete do-file with no documentation |Do-file code to create summary statistics submitted, and well-documented|
|Log-file|Log file missing or in unreadable format |Partial log file included 	|Log file for summary statistics table included 
